# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danvlsv/PSU/OpenSystems/ProfileService-CPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danvlsv/PSU/OpenSystems/ProfileService-CPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danvlsv/PSU/OpenSystems/ProfileService-CPP/CMakeFiles /home/danvlsv/PSU/OpenSystems/ProfileService-CPP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danvlsv/PSU/OpenSystems/ProfileService-CPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named profile_service

# Build rule for target.
profile_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 profile_service
.PHONY : profile_service

# fast build rule for target.
profile_service/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/build
.PHONY : profile_service/fast

src/api_spec.o: src/api_spec.cpp.o
.PHONY : src/api_spec.o

# target to build an object file
src/api_spec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/api_spec.cpp.o
.PHONY : src/api_spec.cpp.o

src/api_spec.i: src/api_spec.cpp.i
.PHONY : src/api_spec.i

# target to preprocess a source file
src/api_spec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/api_spec.cpp.i
.PHONY : src/api_spec.cpp.i

src/api_spec.s: src/api_spec.cpp.s
.PHONY : src/api_spec.s

# target to generate assembly for a file
src/api_spec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/api_spec.cpp.s
.PHONY : src/api_spec.cpp.s

src/handlers/contacts_handler.o: src/handlers/contacts_handler.cpp.o
.PHONY : src/handlers/contacts_handler.o

# target to build an object file
src/handlers/contacts_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/contacts_handler.cpp.o
.PHONY : src/handlers/contacts_handler.cpp.o

src/handlers/contacts_handler.i: src/handlers/contacts_handler.cpp.i
.PHONY : src/handlers/contacts_handler.i

# target to preprocess a source file
src/handlers/contacts_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/contacts_handler.cpp.i
.PHONY : src/handlers/contacts_handler.cpp.i

src/handlers/contacts_handler.s: src/handlers/contacts_handler.cpp.s
.PHONY : src/handlers/contacts_handler.s

# target to generate assembly for a file
src/handlers/contacts_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/contacts_handler.cpp.s
.PHONY : src/handlers/contacts_handler.cpp.s

src/handlers/favorites_handler.o: src/handlers/favorites_handler.cpp.o
.PHONY : src/handlers/favorites_handler.o

# target to build an object file
src/handlers/favorites_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/favorites_handler.cpp.o
.PHONY : src/handlers/favorites_handler.cpp.o

src/handlers/favorites_handler.i: src/handlers/favorites_handler.cpp.i
.PHONY : src/handlers/favorites_handler.i

# target to preprocess a source file
src/handlers/favorites_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/favorites_handler.cpp.i
.PHONY : src/handlers/favorites_handler.cpp.i

src/handlers/favorites_handler.s: src/handlers/favorites_handler.cpp.s
.PHONY : src/handlers/favorites_handler.s

# target to generate assembly for a file
src/handlers/favorites_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/favorites_handler.cpp.s
.PHONY : src/handlers/favorites_handler.cpp.s

src/handlers/handler_factory.o: src/handlers/handler_factory.cpp.o
.PHONY : src/handlers/handler_factory.o

# target to build an object file
src/handlers/handler_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/handler_factory.cpp.o
.PHONY : src/handlers/handler_factory.cpp.o

src/handlers/handler_factory.i: src/handlers/handler_factory.cpp.i
.PHONY : src/handlers/handler_factory.i

# target to preprocess a source file
src/handlers/handler_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/handler_factory.cpp.i
.PHONY : src/handlers/handler_factory.cpp.i

src/handlers/handler_factory.s: src/handlers/handler_factory.cpp.s
.PHONY : src/handlers/handler_factory.s

# target to generate assembly for a file
src/handlers/handler_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/handler_factory.cpp.s
.PHONY : src/handlers/handler_factory.cpp.s

src/handlers/notifications_handler.o: src/handlers/notifications_handler.cpp.o
.PHONY : src/handlers/notifications_handler.o

# target to build an object file
src/handlers/notifications_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/notifications_handler.cpp.o
.PHONY : src/handlers/notifications_handler.cpp.o

src/handlers/notifications_handler.i: src/handlers/notifications_handler.cpp.i
.PHONY : src/handlers/notifications_handler.i

# target to preprocess a source file
src/handlers/notifications_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/notifications_handler.cpp.i
.PHONY : src/handlers/notifications_handler.cpp.i

src/handlers/notifications_handler.s: src/handlers/notifications_handler.cpp.s
.PHONY : src/handlers/notifications_handler.s

# target to generate assembly for a file
src/handlers/notifications_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/notifications_handler.cpp.s
.PHONY : src/handlers/notifications_handler.cpp.s

src/handlers/privacy_handler.o: src/handlers/privacy_handler.cpp.o
.PHONY : src/handlers/privacy_handler.o

# target to build an object file
src/handlers/privacy_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/privacy_handler.cpp.o
.PHONY : src/handlers/privacy_handler.cpp.o

src/handlers/privacy_handler.i: src/handlers/privacy_handler.cpp.i
.PHONY : src/handlers/privacy_handler.i

# target to preprocess a source file
src/handlers/privacy_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/privacy_handler.cpp.i
.PHONY : src/handlers/privacy_handler.cpp.i

src/handlers/privacy_handler.s: src/handlers/privacy_handler.cpp.s
.PHONY : src/handlers/privacy_handler.s

# target to generate assembly for a file
src/handlers/privacy_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/privacy_handler.cpp.s
.PHONY : src/handlers/privacy_handler.cpp.s

src/handlers/profile_handler.o: src/handlers/profile_handler.cpp.o
.PHONY : src/handlers/profile_handler.o

# target to build an object file
src/handlers/profile_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/profile_handler.cpp.o
.PHONY : src/handlers/profile_handler.cpp.o

src/handlers/profile_handler.i: src/handlers/profile_handler.cpp.i
.PHONY : src/handlers/profile_handler.i

# target to preprocess a source file
src/handlers/profile_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/profile_handler.cpp.i
.PHONY : src/handlers/profile_handler.cpp.i

src/handlers/profile_handler.s: src/handlers/profile_handler.cpp.s
.PHONY : src/handlers/profile_handler.s

# target to generate assembly for a file
src/handlers/profile_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/handlers/profile_handler.cpp.s
.PHONY : src/handlers/profile_handler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/repository/contacts_repository.o: src/repository/contacts_repository.cpp.o
.PHONY : src/repository/contacts_repository.o

# target to build an object file
src/repository/contacts_repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/contacts_repository.cpp.o
.PHONY : src/repository/contacts_repository.cpp.o

src/repository/contacts_repository.i: src/repository/contacts_repository.cpp.i
.PHONY : src/repository/contacts_repository.i

# target to preprocess a source file
src/repository/contacts_repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/contacts_repository.cpp.i
.PHONY : src/repository/contacts_repository.cpp.i

src/repository/contacts_repository.s: src/repository/contacts_repository.cpp.s
.PHONY : src/repository/contacts_repository.s

# target to generate assembly for a file
src/repository/contacts_repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/contacts_repository.cpp.s
.PHONY : src/repository/contacts_repository.cpp.s

src/repository/favorites_repository.o: src/repository/favorites_repository.cpp.o
.PHONY : src/repository/favorites_repository.o

# target to build an object file
src/repository/favorites_repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/favorites_repository.cpp.o
.PHONY : src/repository/favorites_repository.cpp.o

src/repository/favorites_repository.i: src/repository/favorites_repository.cpp.i
.PHONY : src/repository/favorites_repository.i

# target to preprocess a source file
src/repository/favorites_repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/favorites_repository.cpp.i
.PHONY : src/repository/favorites_repository.cpp.i

src/repository/favorites_repository.s: src/repository/favorites_repository.cpp.s
.PHONY : src/repository/favorites_repository.s

# target to generate assembly for a file
src/repository/favorites_repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/favorites_repository.cpp.s
.PHONY : src/repository/favorites_repository.cpp.s

src/repository/minio_storage.o: src/repository/minio_storage.cpp.o
.PHONY : src/repository/minio_storage.o

# target to build an object file
src/repository/minio_storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/minio_storage.cpp.o
.PHONY : src/repository/minio_storage.cpp.o

src/repository/minio_storage.i: src/repository/minio_storage.cpp.i
.PHONY : src/repository/minio_storage.i

# target to preprocess a source file
src/repository/minio_storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/minio_storage.cpp.i
.PHONY : src/repository/minio_storage.cpp.i

src/repository/minio_storage.s: src/repository/minio_storage.cpp.s
.PHONY : src/repository/minio_storage.s

# target to generate assembly for a file
src/repository/minio_storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/minio_storage.cpp.s
.PHONY : src/repository/minio_storage.cpp.s

src/repository/notifications_repository.o: src/repository/notifications_repository.cpp.o
.PHONY : src/repository/notifications_repository.o

# target to build an object file
src/repository/notifications_repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/notifications_repository.cpp.o
.PHONY : src/repository/notifications_repository.cpp.o

src/repository/notifications_repository.i: src/repository/notifications_repository.cpp.i
.PHONY : src/repository/notifications_repository.i

# target to preprocess a source file
src/repository/notifications_repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/notifications_repository.cpp.i
.PHONY : src/repository/notifications_repository.cpp.i

src/repository/notifications_repository.s: src/repository/notifications_repository.cpp.s
.PHONY : src/repository/notifications_repository.s

# target to generate assembly for a file
src/repository/notifications_repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/notifications_repository.cpp.s
.PHONY : src/repository/notifications_repository.cpp.s

src/repository/privacy_repository.o: src/repository/privacy_repository.cpp.o
.PHONY : src/repository/privacy_repository.o

# target to build an object file
src/repository/privacy_repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/privacy_repository.cpp.o
.PHONY : src/repository/privacy_repository.cpp.o

src/repository/privacy_repository.i: src/repository/privacy_repository.cpp.i
.PHONY : src/repository/privacy_repository.i

# target to preprocess a source file
src/repository/privacy_repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/privacy_repository.cpp.i
.PHONY : src/repository/privacy_repository.cpp.i

src/repository/privacy_repository.s: src/repository/privacy_repository.cpp.s
.PHONY : src/repository/privacy_repository.s

# target to generate assembly for a file
src/repository/privacy_repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/privacy_repository.cpp.s
.PHONY : src/repository/privacy_repository.cpp.s

src/repository/profile_repository.o: src/repository/profile_repository.cpp.o
.PHONY : src/repository/profile_repository.o

# target to build an object file
src/repository/profile_repository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/profile_repository.cpp.o
.PHONY : src/repository/profile_repository.cpp.o

src/repository/profile_repository.i: src/repository/profile_repository.cpp.i
.PHONY : src/repository/profile_repository.i

# target to preprocess a source file
src/repository/profile_repository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/profile_repository.cpp.i
.PHONY : src/repository/profile_repository.cpp.i

src/repository/profile_repository.s: src/repository/profile_repository.cpp.s
.PHONY : src/repository/profile_repository.s

# target to generate assembly for a file
src/repository/profile_repository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/repository/profile_repository.cpp.s
.PHONY : src/repository/profile_repository.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/profile_service.dir/build.make CMakeFiles/profile_service.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... profile_service"
	@echo "... src/api_spec.o"
	@echo "... src/api_spec.i"
	@echo "... src/api_spec.s"
	@echo "... src/handlers/contacts_handler.o"
	@echo "... src/handlers/contacts_handler.i"
	@echo "... src/handlers/contacts_handler.s"
	@echo "... src/handlers/favorites_handler.o"
	@echo "... src/handlers/favorites_handler.i"
	@echo "... src/handlers/favorites_handler.s"
	@echo "... src/handlers/handler_factory.o"
	@echo "... src/handlers/handler_factory.i"
	@echo "... src/handlers/handler_factory.s"
	@echo "... src/handlers/notifications_handler.o"
	@echo "... src/handlers/notifications_handler.i"
	@echo "... src/handlers/notifications_handler.s"
	@echo "... src/handlers/privacy_handler.o"
	@echo "... src/handlers/privacy_handler.i"
	@echo "... src/handlers/privacy_handler.s"
	@echo "... src/handlers/profile_handler.o"
	@echo "... src/handlers/profile_handler.i"
	@echo "... src/handlers/profile_handler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/repository/contacts_repository.o"
	@echo "... src/repository/contacts_repository.i"
	@echo "... src/repository/contacts_repository.s"
	@echo "... src/repository/favorites_repository.o"
	@echo "... src/repository/favorites_repository.i"
	@echo "... src/repository/favorites_repository.s"
	@echo "... src/repository/minio_storage.o"
	@echo "... src/repository/minio_storage.i"
	@echo "... src/repository/minio_storage.s"
	@echo "... src/repository/notifications_repository.o"
	@echo "... src/repository/notifications_repository.i"
	@echo "... src/repository/notifications_repository.s"
	@echo "... src/repository/privacy_repository.o"
	@echo "... src/repository/privacy_repository.i"
	@echo "... src/repository/privacy_repository.s"
	@echo "... src/repository/profile_repository.o"
	@echo "... src/repository/profile_repository.i"
	@echo "... src/repository/profile_repository.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

